// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9VoNRBkowpHBsdV_tEKCBidj0SHSVIk',
    appId: '1:302060725266:web:48a6f8bda11fb8e6e324cb',
    messagingSenderId: '302060725266',
    projectId: 'novelux-1a13a',
    authDomain: 'novelux-1a13a.firebaseapp.com',
    storageBucket: 'novelux-1a13a.firebasestorage.app',
    measurementId: 'G-37SKM5S9LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLs9mxq5mazCncdBhY5XOrQdvQ4RyT7Fk',
    appId: '1:302060725266:android:bcdc3864fbd7c5a5e324cb',
    messagingSenderId: '302060725266',
    projectId: 'novelux-1a13a',
    storageBucket: 'novelux-1a13a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsG8CoM8q1Hvq23YCnhriiLZASFlQEsk',
    appId: '1:302060725266:ios:42361e95548190f0e324cb',
    messagingSenderId: '302060725266',
    projectId: 'novelux-1a13a',
    storageBucket: 'novelux-1a13a.firebasestorage.app',
    iosBundleId: 'com.daniel.novelux.novelux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsG8CoM8q1Hvq23YCnhriiLZASFlQEsk',
    appId: '1:302060725266:ios:42361e95548190f0e324cb',
    messagingSenderId: '302060725266',
    projectId: 'novelux-1a13a',
    storageBucket: 'novelux-1a13a.firebasestorage.app',
    iosBundleId: 'com.daniel.novelux.novelux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9VoNRBkowpHBsdV_tEKCBidj0SHSVIk',
    appId: '1:302060725266:web:ec12e2fd0c114837e324cb',
    messagingSenderId: '302060725266',
    projectId: 'novelux-1a13a',
    authDomain: 'novelux-1a13a.firebaseapp.com',
    storageBucket: 'novelux-1a13a.firebasestorage.app',
    measurementId: 'G-KEGVJ7FEFZ',
  );
}
